#!/system/bin/sh
set -e

log -t SBS "Is installed"
if [ -e /data/system/sbs/enabled -o -e /data/system/sbs/permanent ] ; then
    log -t SBS "Is enabled"
    rm -f /data/system/sbs/enabled
    log -t SBS "Ok, use libsurfaceflinger.so with SBS support"
    export LD_LIBRARY_PATH=/data/system/sbs
else
    log -t SBS "Is not enabled"
fi
exec /system/bin/surfaceflinger.real $*
